import React, { ReactNode } from 'react';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { UserProvider } from '@/components/hooks/userContext';
import { ArticlesProvider } from '@/components/hooks/articlesContext';

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: ReactNode }) {
    return (
        <html lang="de">
            <body>
                <AppRouterCacheProvider>
                    <UserProvider>
                        <ArticlesProvider>{children}</ArticlesProvider>
                    </UserProvider>
                </AppRouterCacheProvider>
            </body>
        </html>
    );
}
