import React, { ReactNode } from 'react';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { UserProvider } from '@/components/hooks/userContext';
import { ArticlesProvider } from '@/components/hooks/articlesContext';
import { CssBaseline, ThemeProvider } from '@mui/material';
import theme from '@/theme';
import { CartProvider } from '@/components/hooks/cartContext';
import '../css/global.css';
import { StyledEngineProvider } from '@mui/styled-engine';

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: ReactNode }) {
    return (
        <html lang="de">
            <AppRouterCacheProvider>
                <StyledEngineProvider injectFirst>
                    <ThemeProvider theme={theme}>
                        <UserProvider>
                            <ArticlesProvider>
                                <CartProvider>
                                    <body style={{ margin: '20px' }}>{children}</body>
                                </CartProvider>
                                <CssBaseline />
                            </ArticlesProvider>
                        </UserProvider>
                    </ThemeProvider>
                </StyledEngineProvider>
            </AppRouterCacheProvider>
        </html>
    );
}
