import React, { ReactNode } from 'react';

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: ReactNode }) {
    return (
        <>
            {/*<ProfilePic width={60} height={60} />*/}
            {children}
        </>
    );
}
