import React, { ReactElement } from 'react';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { UserProvider } from '@/components/hooks/userContext';
import { ArticlesProvider } from '@/components/hooks/articlesContext';
import { CssBaseline, ThemeProvider } from '@mui/material';
import theme from '@/theme';
import { CartProvider } from '@/components/hooks/cartContext';
import '../../css/global.css';
import { StyledEngineProvider } from '@mui/styled-engine';
import { PageParams } from '@/lib/schemas/locale.schema';
import { I18nProviderClient } from '@/locales/client';

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
};

export default function RootLayout({
    children,
    params: { locale },
}: {
    children: ReactElement;
} & PageParams) {
    return (
        <html lang={locale}>
            <AppRouterCacheProvider>
                <StyledEngineProvider injectFirst>
                    <ThemeProvider theme={theme}>
                        <UserProvider>
                            <ArticlesProvider>
                                <CartProvider>
                                    <I18nProviderClient locale={locale}>
                                        <body className={'m-[20px]'}>{children}</body>
                                    </I18nProviderClient>
                                </CartProvider>
                                <CssBaseline />
                            </ArticlesProvider>
                        </UserProvider>
                    </ThemeProvider>
                </StyledEngineProvider>
            </AppRouterCacheProvider>
        </html>
    );
}
